openapi: 3.1.0
info:
  title: Roan Universal Assistant API
  version: 1.0.0
  description: Access Gmail, Calendar, Drive, Tasks, and Contacts for Zädi using a unified API.

servers:
  - url: https://web-production-cf55.up.railway.app

paths:
  /calendar/all:
    get:
      operationId: getCalendarEvents
      summary: Get upcoming Google Calendar events
      responses:
        '200':
          description: A list of upcoming calendar events.

  /gmail/threads:
    get:
      operationId: getGmailThreads
      summary: Get Gmail threads
      responses:
        '200':
          description: A list of Gmail threads.

  /gmail/send:
    post:
      operationId: sendGmailMessage
      summary: Send a Gmail message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                subject:
                  type: string
                body:
                  type: string
      responses:
        '200':
          description: Sent message metadata

  /drive/files:
    get:
      operationId: listDriveFiles
      summary: List files in Google Drive
      responses:
        '200':
          description: A list of files in Drive.

  /drive/upload:
    post:
      operationId: uploadDriveFile
      summary: Upload a file to Google Drive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_name:
                  type: string
                file_path:
                  type: string
      responses:
        '200':
          description: Uploaded file metadata

  /tasks/all:
    get:
      operationId: getTasks
      summary: Get all Google Tasks
      responses:
        '200':
          description: A list of tasks by task list.

  /tasks/add:
    post:
      operationId: addTask
      summary: Add a new Google Task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tasklist_id:
                  type: string
                task:
                  type: object
      responses:
        '200':
          description: The created task

  /contacts/search:
    post:
      operationId: searchContacts
      summary: Search your Google Contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Matching contact results

  /contacts/create:
    post:
      operationId: createContact
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
      responses:
        '200':
          description: The created contact

  /contacts/update:
    put:
      operationId: updateContact
      summary: Update a contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resourceName:
                  type: string
                update:
                  type: object
      responses:
        '200':
          description: The updated contact

  /contacts/delete:
    delete:
      operationId: deleteContact
      summary: Delete a contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resourceName:
                  type: string
      responses:
        '200':
          description: Deletion confirmation
